name: Void.Json - Publish Nuget

#on: [push]
on:
  push:
    branches:
      - void_json_pack
  pull_request:
    branches:
      - void_json_pack

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: 3.0.100    
        # source-url: https://nuget.pkg.github.com/<owner>/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.VOID_BOX_NUGET_KEY}}
    
    - name: Build the solution
      run: dotnet build --configuration Release
      
    - name: Create the package
      run: dotnet pack --configuration Release Void.Json
      
    - name: Publish the package to GPR
      run: dotnet nuget push Void.Json/bin/Release/*.nupkg -k ${{secrets.VOID_BOX_NUGET_KEY}} -s https://api.nuget.org/v3/index.json
